### ISSUE TITLE
Hide My Ass VPN support 

### ISSUE THREAD

**Issue by HaxorGaruda** [corrad1nho/qomui#21]
please add compability for hide my ass config ovpn support, after select folder config all hma , it's app force close..

**Comment by corrad1nho** [comment]
Hi,

I'm very sorry that didn't work. I tried adding all HMA config files downloaded from https://vpn.hidemyass.com/vpn-config/OpenVPN-2.4/UDP/ and couldn't find any issue except that there are no flags displayed for some of the countries (I might add the missing ones in the future). I can't really test anything else because I have no HMA subscription. I assume you are using different config files and there is an uncaught exception. Can you start Qomui from a terminal (just type "qomui-gui") and post the output after it crashes? I'm sure I can fix the error quickly. 

Other things that would be helpful to know: Which distribution are you currently using, which version of Qomui is installed and how did you install it? If you installed Qomui from source: Are all dependencies satisfied? Particularly, make sure that "dig" is installed on your system and working properly - you can try that by typing the following command in a terminal:

``dig google.com``

It should return DNS information for google.com.

**Comment by HaxorGaruda** [comment]
i got this error from terminal : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/qomui/update.py", line 672, in run
    self.import_configs()
  File "/usr/local/lib/python3.6/dist-packages/qomui/update.py", line 755, in import_configs
    country = country_translate(cc)
  File "/usr/local/lib/python3.6/dist-packages/qomui/update.py", line 32, in country_translate
    with open("countries.json", "r") as c_json:
FileNotFoundError: [Errno 2] No such file or directory: 'countries.json'
[1]    8353 abort      qomui-gui

```
u can use my subcription for testing ...

**Comment by corrad1nho** [comment]
Now I understand. Even if you install from source it's better to use the releases - I should actually add that to the readme. Your issue was a temporary bug that is already fixed. Just install the latest release (v0.6.5) or via git clone/setup.py and you should be able to add HMA configs.

**Comment by HaxorGaruda** [comment]
nice release again n again.. thanks brother.. you make me smile ..

**Comment by corrad1nho** [comment]
Thanks! I guess the issue has been resolved then?
